Followers
crowdriff/twitter pull request #26
Opened 2016-10-14 01:09 UTC by massanishi

2016-10-14 02:43 UTC, ryanfowler requested changes
👍 Just have a few comments

2016-10-14 02:43 UTC, ryanfowler commented on followers.go
> +	IncludeUserEntities bool
Should be `ExcludeUserEntities`, so that we will only use this field if set to `true`.

2016-10-14 02:43 UTC, ryanfowler commented on followers.go
> +	var users map[string][]User
Instead of using a `map[string][]User`, use the type:
```go
type UserList struct {
    Users []User `json:"users"`
}
```

2016-10-14 02:43 UTC, ryanfowler commented on followers.go
> +		values.Set("skip_status", "false")
The text here should be `"true"` if `SkipStatus` is true.

2016-10-14 02:43 UTC, ryanfowler commented on followers.go
> +		values.Set("include_entities", "false")
Should be:
```go
if params.ExcludeUserEntities {
    values.Set("include_entities", "false")
}
```

2016-10-14 02:43 UTC, ryanfowler commented on followers.go
> +type FollowerIDsParams struct {
Public type declaration needs a comment.

2016-10-14 02:43 UTC, ryanfowler commented on model.go
> +	IDs               []int  `json:"ids"`
Should be `int64` (the type for all Twitter numerical IDs). Does this endpoint return an `id_strs` field as well?

2016-10-14 02:43 UTC, ryanfowler commented on twitter.go
> +	Users     map[string][]User
Use: 
```go
type UserList struct {
    Users []User `json:"users"`
}
```

2016-10-16 21:56 UTC, abh1nav commented
@ryanfowler also added in Friends endpoints here because they're identical to Followers. Fixes #30 .

2016-10-17 02:36 UTC, closed without merging